---
addons:
  apt:
    packages:
      - g++-4.8
    sources:
      - ubuntu-toolchain-r-test
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "7.0.0"
before_script:
  - "npm install"
script:
  - "npm run everything"
